" Pathogen
let g:pathogen_disabled = ['pathogen']
execute pathogen#infect()

" The most important of keybinds
let mapleader = ","

" Ignored Compiled Files
set wildignore+=*.o,*~,*.pyc,*.class

" Statusbar stuff / vim-airline
set laststatus=2
let g:airline#extensions#tabline#enabled = 1
let g:airline_powerline_fonts = 1

" Line numbers
set number

" Search stuff
set ignorecase
set hlsearch
set incsearch

" Text stuff
syntax enable
set encoding=utf8
set synmaxcol=2048
set nocursorline
set nocursorcolumn

" Tab stuff
filetype plugin indent on
set expandtab
set smarttab
set shiftwidth=4
set tabstop=4
set lbr
set tw=500
set ai
set si
set wildmenu
set wildmode=longest:full,full

" Get rid of swap files
set nobackup
set nowb
set noswapfile

" Auto reload files on disk
set autoread

" Trailing spaces suck
autocmd FileType c,cpp,java,scala,html,coffee,ts autocmd BufWritePre <buffer> :%s/\s\+$//e

" Mutt settings
au BufRead /tmp/mutt-* set tw=72
au BufRead /tmp/mutt-* set fo+=aw

" CtrlP Settings
let g:ctrlp_custom_ignore = '\v%(/\.%(git|hg|svn)|\.%(class|o|png|jpg|jpeg|bmp|tar|jar|tgz|deb|zip)$|/%(target|build)/)'
map <leader>b :CtrlPBuffer<CR>

" Python-Mode settings
let g:pymode_rope = 0
let g:pymode_folding = 0
let g:pymode_warnings = 0
let g:pymode_lint_ignore = 'E501'

" Stuff should only have 2 spaces
au FileType html :setlocal sw=2 ts=2
au FileType javascript :setlocal sw=2 ts=2
au FileType coffee :setlocal sw=2 ts=2
au FileType scala :setlocal sw=2 ts=2
au FileType xml :setlocal sw=2 ts=2
au FileType dot :setlocal sw=2 ts=2
au FileType rust :setlocal sw=2 ts=2
au FileType stylus :setlocal sw=2 ts=2
au FileType yaml :setlocal sw=2 ts=2

" Gradle
au BufNewFile,BufRead *.gradle setf groovy

" Markdown
autocmd FileType * unlet! g:airline#extensions#whitespace#checks
autocmd FileType markdown let g:airline#extensions#whitespace#checks = [ 'indent' ]

" Keybinds
command! W :execute ':silent w !sudo tee % > /dev/null' | :edit!
map <C-Tab> :bnext<cr>
map <C-S-Tab> :bprevious<cr>
map <leader>gb :Gblame<cr>
