---
- name: install hyprland and related packages
  become: yes
  package:
    name:
      - hyprland
      - xdg-desktop-portal-hyprland
      - hyprpolkitagent
      - hyprlock
      - hypridle
    state: present

- name: install hyprland utilities
  become: yes
  package:
    name:
      - alacritty
      - rofi
      - dunst
      - thunar
      - cliphist
    state: present
