---
- name: Install desktop system utilities
  become: yes
  package:
    name:
      - brightnessctl
      - upower
      - bluez
      - tlp
      - tlp-rdw
    state: present

- name: Enable system services
  become: yes
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
  loop:
    - bluetooth.service
    - upower.service
    - tlp.service
    - NetworkManager-dispatcher.service

- name: link tlp configuration
  become: yes
  file:
    src: "{{ role_path }}/files/99-tlp.conf"
    dest: "/etc/tlp.d/99-tlp.conf"
    state: link
    force: true
