" Pathogen
let g:pathogen_disabled = ['pathogen']
execute pathogen#infect()
filetype plugin indent on

" Ignored Compiled Files
set wildignore=*.o,*~,*.pyc

" Search stuff
set ignorecase
set hlsearch
set incsearch

" Text stuff
syntax enable
set encoding=utf8

" Tab stuff
set expandtab
set smarttab
set shiftwidth=4
set tabstop=4
set lbr
set tw=500
set ai
set si

" Get rid of swap files
set nobackup
set nowb
set noswapfile

" Mutt settings
au BufRead /tmp/mutt-* set tw=72
au BufRead /tmp/mutt-* set fo+=aw

" CtrlP Settings
let g:ctrlp_custom_ignore = {
  \ 'dir': '\v[\/]\.(git|hg|svn)$',
  \}

" Python-Mode settings
let g:pymode_rope = 1
let g:pymode_folding = 0

" Keybinds
cmap w!! w !sudo tee > /dev/null %
