" Pathogen
let g:pathogen_disabled = ['pathogen']
execute pathogen#infect()
filetype plugin indent on

" The most important of keybinds
let mapleader = ","

" Ignored Compiled Files
set wildignore+=*.o,*~,*.pyc,*.class

" Statusbar stuff / vim-airline
set laststatus=2
let g:airline#extensions#tabline#enabled = 1
let g:airline_powerline_fonts = 1

" Line numbers
set number

" Search stuff
set ignorecase
set hlsearch
set incsearch

" Text stuff
syntax enable
set encoding=utf8
set synmaxcol=2048
set nocursorline
set nocursorcolumn

" Tab stuff
set expandtab
set smarttab
set shiftwidth=4
set tabstop=4
set lbr
set tw=500
set ai
set si

" Get rid of swap files
set nobackup
set nowb
set noswapfile

" Auto reload files on disk
set autoread

" Mutt settings
au BufRead /tmp/mutt-* set tw=72
au BufRead /tmp/mutt-* set fo+=aw

" CtrlP Settings
let g:ctrlp_custom_ignore = '\v%(/\.%(git|hg|svn)|\.%(class|o|png|jpg|jpeg|bmp|tar|jar|tgz|deb|zip)$|/%(target|build)/)'
map <leader>b :CtrlPBuffer<CR>

" Python-Mode settings
let g:pymode_rope = 1
let g:pymode_folding = 0

" Keybinds
command! W :execute ':silent w !sudo tee % > /dev/null' | :edit!
