#! /bin/sh

if [ $(pgrep -cx panel) -gt 1 ] ; then
    printf "%s\n" "The panel is already running." >&2
    exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

# Configure
source $(dirname $0)/panel_config

bspc config top_padding 20

# Setup FIFO Pipe
[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"
bspc control --subscribe > "$PANEL_FIFO" &

# Text Output Programs
xtitle -sf 'T%s' > "$PANEL_FIFO" &
clock -sf 'S%a %H:%M' > "$PANEL_FIFO" &

# Run
cat "$PANEL_FIFO" \
    | ./panel_bar \
    | lemonbar \
        -g "x20" \
        #-f "$PANEL_FONT_FAMILY" \
        -F "$COLOR_FOREGROUND" \
        -B "$COLOR_BACKGROUND" &

wait
