---
- include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family.split()[0] | lower }}.yml"
    - "default.yml"

- import_tasks: shell-tools.yml
- import_tasks: vim.yml
- import_tasks: gitssh.yml
