---
- name: install neo vim
  become: yes
  package:
    name: neovim
    state: present

- name: link vimrc
  file:
    src: "{{ role_path }}/files/vimrc"
    dest: "{{ ansible_facts['env']['HOME'] }}/.vimrc"
    state: link
    force: true

- name: Symlink nvim config
  file:
    src: "{{ role_path }}/files/nvim"
    dest: "~/.config/nvim"
    state: link
    force: true
