#--------------------------------------------------------------------
#   General Config
#--------------------------------------------------------------------
set -g prefix C-a
set -g base-index 1
set -g mode-keys vi
set -g status-keys vi
set -sg escape-time 0
set -g default-command "/usr/bin/zsh"
set -g default-terminal tmux-256color

#--------------------------------------------------------------------
#   GUI/Mouse Support
#--------------------------------------------------------------------

set -g mouse on
set -s set-clipboard on
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel

#--------------------------------------------------------------------
#   Keybinds
#--------------------------------------------------------------------
unbind C-b
unbind c
unbind %
unbind '"'

bind-key C-a last-window
bind-key : command-prompt

bind-key Enter new-window
bind-key c split-window -v
bind-key C split-window -h

bind -n M-Left select-pane -L
bind -n M-Down select-pane -D
bind -n M-Up select-pane -U
bind -n M-Right select-pane -R

bind-key C-h resize-pane -L 1
bind-key C-j resize-pane -D 1
bind-key C-k resize-pane -U 1
bind-key C-l resize-pane -R 1

#--------------------------------------------------------------------
#   Apperance
#--------------------------------------------------------------------
set -gq @thm_bg               "default"
set -gq @thm_bar_bg           "default"
set -gq @thm_fg               "colour252"
set -gq @thm_primary          "colour255"
set -gq @thm_inverse_primary  "colour234"
set -gq @thm_surface_low      "default"
set -gq @thm_surface          "colour236"
set -gq @thm_surface_variant  "colour238"
set -gq @thm_outline          "colour240"
set -gq @thm_text_variant     "colour245"

# Override with matugen-generated palette if present
source-file -q "~/.config/tmux/colors.conf"

set -g set-titles on

set -g status-left-length  60
set -g status-left  "#[fg=#{@thm_primary},bold] #S #[fg=#{@thm_text_variant},nobold]• #(whoami) "

set -g status-right-length 60
set -g status-right "#[fg=#{@thm_text_variant}]#H • #(uname -r) "

set -g status-style     "bg=#{@thm_bar_bg},fg=#{@thm_fg}"
set -g status-interval  4
set -g status-justify   centre
set -g status-position  top

setw -g window-status-current-style  "fg=#{@thm_inverse_primary},bg=#{@thm_primary},bold"
setw -g window-status-style          "fg=#{@thm_text_variant},bg=#{@thm_bar_bg}"
setw -g window-status-separator      " "
setw -g window-status-format         " #I #W "
setw -g window-status-current-format " #I #W "

set -g pane-border-style        "fg=#{@thm_outline},bg=default"
set -g pane-active-border-style "fg=#{@thm_primary},bg=default"

#--------------------------------------------------------------------
#   Audio
#--------------------------------------------------------------------
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
set -g bell-action none
setw -g monitor-activity off
