#!/bin/sh
#--------------------------------------------------------------------
#   xinitrc
#--------------------------------------------------------------------

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

[[ -f ~/.Xresources ]] && xrdb -merge ~/.Xresources

#--------------------------------------------------------------------
#   Daemons
#--------------------------------------------------------------------
/usr/bin/urxvtd -q -f -o
#/usr/bin/mpd ~/.mpd/mpd.conf

#--------------------------------------------------------------------
#   Programs
#--------------------------------------------------------------------
xcompmgr -c &
nm-applet &
nautilus --no-desktop -n &

#--------------------------------------------------------------------
#   WM + Enviroment
#--------------------------------------------------------------------
hsetroot -center ~/wallpaper.jpg
#hsetroot -fill /path/to/background/image
#setxkbmap us -variant colemak
exec dbus-launch xmonad
