---
- name: create user font directory
  file: "path={{ ansible_env.HOME }}/.fonts state=directory"

- name: install inconsolata
  package:
    name: ttf-inconsolata
    state: present

- name: install inconsolata powerline
  get_url:
    url: https://github.com/powerline/fonts/raw/master/Inconsolata/Inconsolata%20for%20Powerline.otf
    dest: "{{ ansible_env.HOME }}/.fonts/inconsolata-powerline.otf"
  notify:
    - rebuild font cache
