---
- name: install tmux
  become: yes
  package:
    name: tmux
    state: present

- name: link tmux.conf
  file:
    src: "{{ role_path }}/files/tmux.conf"
    dest: "{{ ansible_facts['env']['HOME'] }}/.tmux.conf"
    state: link
    force: yes

# for additional scripts / configuration
- name: create tmux config directory
  file:
    path: "{{ ansible_facts['env']['HOME'] }}/.config/tmux"
    state: directory

- name: link tmux git helper
  file:
    src: "{{ role_path }}/files/tmux-git-segment.sh"
    dest: "{{ ansible_facts['env']['HOME'] }}/.config/tmux/git-segment.sh"
    state: link
    force: yes
