---
- name: install zsh
  become: yes
  package:
    name: zsh
    state: present

- name: ensure zsh plugin directory
  become: yes
  file: "path=/usr/share/zsh/plugins state=directory"

- name: install zsh syntax highlighting
  become: yes
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: /usr/share/zsh/plugins/zsh-syntax-highlighting

- name: link zsh config
  file:
    src: "{{ role_path }}/files/zshrc"
    dest: "{{ ansible_env.HOME }}/.zshrc"
    state: link
    force: yes
