---
- name: install zsh
  package:
    name: zsh
    state: present

- name: install zsh syntax highlighting
  package:
    name: zsh-syntax-highlighting
    state: present

- name: install zsh history search
  package:
    name: zsh-history-substring-search
    state: present

- name: link zsh config
  file:
    src: "{{ role_path }}/files/zshrc"
    dest: "{{ ansible_env.HOME }}/.zshrc"
    state: link
    force: yes
