---
- name: install zsh
  become: yes
  package:
    name: zsh
    state: present

- name: ensure zsh plugin directory
  become: yes
  file: "path=/usr/share/zsh/plugins state=directory"

- name: install zsh syntax highlighting
  become: yes
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: /usr/share/zsh/plugins/zsh-syntax-highlighting

- name: set zsh as default shell
  become: yes
  user:
    name: "{{ ansible_user_id }}"
    shell: /usr/bin/zsh

- name: link zsh config
  file:
    src: "{{ role_path }}/files/zshrc"
    dest: "{{ ansible_facts['env']['HOME'] }}/.zshrc"
    state: link
    force: yes

- name: link zsh profile
  file:
    src: "{{ role_path }}/files/zprofile"
    dest: "{{ ansible_facts['env']['HOME'] }}/.zprofile"
    state: link
    force: yes
